Repository yazilimacademy/akilliprompt-backend, pull requests merged in 2024-11, with the labels that each got.

#4 [Fix]: readme.md and license files updated.
  LICENSE.md
  README.md
Labels: documentation, good first issue

#5 [Fix]: readme.md and license files updated.
  README.md
  logos/logo_240x202.png
  logos/yazilim_academy_logo_240.png
Labels: documentation

#7 [Fix]: Images updated for README file
  README.md
Labels: documentation, help wanted

#8 CQRS operations for the Category entity are completed.
  src/AkilliPrompt.Domain/Entities/Category.cs
  src/AkilliPrompt.WebApi/Behaviors/ValidationBehavior.cs
  src/AkilliPrompt.WebApi/DependencyInjection.cs
  src/AkilliPrompt.WebApi/Filters/ValidationFilter.cs
  src/AkilliPrompt.WebApi/V1/Categories/CategoriesController.cs
  src/AkilliPrompt.WebApi/V1/Categories/Commands/Create/CreateCategoryCommand.cs
  src/AkilliPrompt.WebApi/V1/Categories/Commands/Create/CreateCategoryCommandHandler.cs
  src/AkilliPrompt.WebApi/V1/Categories/Commands/Create/CreateCategoryCommandValidator.cs
  src/AkilliPrompt.WebApi/V1/Categories/Commands/Delete/DeleteCategoryCommand.cs
  src/AkilliPrompt.WebApi/V1/Categories/Commands/Delete/DeleteCategoryCommandHandler.cs
  src/AkilliPrompt.WebApi/V1/Categories/Commands/Delete/DeleteCategoryValidator.cs
  src/AkilliPrompt.WebApi/V1/Categories/Commands/Update/UpdateCategoryCommand.cs
  src/AkilliPrompt.WebApi/V1/Categories/Commands/Update/UpdateCategoryCommandHandler.cs
  src/AkilliPrompt.WebApi/V1/Categories/Commands/Update/UpdateCategoryCommandValidator.cs
  src/AkilliPrompt.WebApi/V1/Categories/Create/CreateCategoryDto.cs
  src/AkilliPrompt.WebApi/V1/Categories/Queries/GetAll/GetAllCategoriesDto.cs
  src/AkilliPrompt.WebApi/V1/Categories/Queries/GetAll/GetAllCategoriesQuery.cs
  src/AkilliPrompt.WebApi/V1/Categories/Queries/GetAll/GetAllCategoriesQueryHandler.cs
  src/AkilliPrompt.WebApi/V1/Categories/Queries/GetById/GetByIdCategoryDto.cs
  src/AkilliPrompt.WebApi/V1/Categories/Queries/GetById/GetByIdCategoryQuery.cs
  src/AkilliPrompt.WebApi/V1/Categories/Queries/GetById/GetByIdCategoryQueryHandler.cs
  src/AkilliPrompt.WebApi/V1/Categories/Queries/GetById/GetByIdCategoryQueryValidator.cs
  src/AkilliPrompt.WebApi/V1/Categories/UpdateCategoryDto.cs
Labels: documentation, enhancement, good first issue

#9 Distributed Caching added via Dragonfly
  .gitignore
  src/AkilliPrompt.Domain/Common/ICacheable.cs
  src/AkilliPrompt.WebApi/AkilliPrompt.WebApi.csproj
  src/AkilliPrompt.WebApi/Behaviors/CachingBehavior.cs
  src/AkilliPrompt.WebApi/DependencyInjection.cs
  src/AkilliPrompt.WebApi/Helpers/CacheKeysHelper.cs
  src/AkilliPrompt.WebApi/Logs/log20241123.txt
  src/AkilliPrompt.WebApi/Program.cs
  src/AkilliPrompt.WebApi/Services/CacheInvalidator.cs
  src/AkilliPrompt.WebApi/Services/ICacheInvalidator.cs
  src/AkilliPrompt.WebApi/V1/Categories/Commands/Create/CreateCategoryCommandHandler.cs
  src/AkilliPrompt.WebApi/V1/Categories/Commands/Create/CreateCategoryCommandValidator.cs
  src/AkilliPrompt.WebApi/V1/Categories/Commands/Update/UpdateCategoryCommandHandler.cs
  src/AkilliPrompt.WebApi/V1/Categories/Queries/GetAll/GetAllCategoriesQuery.cs
  src/AkilliPrompt.WebApi/V1/Categories/Queries/GetAll/GetAllCategoriesQueryHandler.cs
  src/AkilliPrompt.WebApi/V1/Categories/Queries/GetById/GetByIdCategoryQuery.cs
  src/AkilliPrompt.WebApi/appsettings.json
Labels: documentation, enhancement, good first issue
